version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: linzongpei/faiss-web-service:test35
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "8"
          memory: 2000M
      restart_policy:
        condition: on-failure
    ports:
      - "4001:5000"
    networks:
      - webnet
networks:
  webnet: